name: Test Backend with Postman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Node.js pour le backend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Étape 3 : Installer les dépendances backend
      - name: Install Backend Dependencies
        run: npm ci
        working-directory: ./server

      # Étape 4 : Configurer MySQL
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1
        with:
          mysql version: '8.0'
          mysql database: ${{ secrets.DB_NAME }}
          mysql user: ${{ secrets.DB_USERNAME }}
          mysql password: ${{ secrets.DB_PASSWORD }}

      # Étape 5 : Créer le fichier .env
      - name: Create .env File
        run: |
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> ./server/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ./server/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> ./server/.env
          echo "DB_HOST=127.0.0.1" >> ./server/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> ./server/.env
          echo "PORT=3000" >> ./server/.env

      # Étape 6 : Attendre que MySQL démarre complètement
      - name: Wait for MySQL
        run: sleep 60

      # Étape 7 : Effectuer les migrations et seed
      - name: Run migrations
        run: npx sequelize-cli db:migrate --debug
        working-directory: ./server

      - name: Run seeds
        run: npx sequelize-cli db:seed:all
        working-directory: ./server

      # Étape 8 : Démarrer le serveur backend
      - name: Start Backend Server
        run: npm run serve &
        working-directory: ./server

      # Attendre que le serveur démarre
      - name: Wait for server to start
        run: sleep 10

      # Étape 9 : Installer Newman pour exécuter les tests Postman
      - name: Install Newman
        run: npm install -g newman

      # Étape 10 : Exécuter les tests Postman
      - name: Run Postman Tests
        run: |
          newman run ./server/tests/collection.json \
          --environment ./server/tests/environment.json
